### ISSUE TITLE
Gradio demo available

### ISSUE THREAD

**Issue by fffiloni** [MeiGen-AI/MultiTalk#39]
Hello 👋

I’ve crafted a Gradio App available here: https://huggingface.co/spaces/fffiloni/Meigen-MultiTalk

Works with L40S, multi-GPU ready.
Shared UI on HF is limited to 5 seconds audio max and 12 sample_steps. Results with 12 steps are satisfying enough for the demo purpose.

Performances on L40S are quite similar than on A100, maybe loosing around 10 seconds at each step.

You can duplicate the space to your own account to unlock these limitations ;)

Enjoy ! 

PS: see the requirements.txt file to understand how to handle some of your struggles installing dependencies 🤗

**Comment by nguyenkienleho** [comment]
hi can i install this with RTX 5090 thank you for sharing

**Comment by fffiloni** [comment]
@Pblaz : This is due to the gradio queue being full :)

You might want to duplicate to skip it

**Comment by laurbrick** [comment]
When I duplicate the Demo on HuggingFace I get a stripped down interface that is not fully functioning. Is there a way to get the exact Demo version shown? 

![Image](https://github.com/user-attachments/assets/b5e85a89-1097-4df4-974c-d94c61c63dbc)

**Comment by doggiedaddy69** [comment]
> Any chance to run this on local 5090?!

Following

**Comment by samyaksgupta** [comment]
hey i am getting the same error while running , showing the same inference error,

**Comment by alexyeoh** [comment]
even after duplicating the space, it's not working anymore. I am always hit with the same Inference Error too.

**Comment by fffiloni** [comment]
Hello everyone 👋 

sorry for the late response, i was off for a couple of days. 

The problem was due to an incompatibility with newest transformers version, so i fixed the demo by specifying the right module versions.

I’ve tested it, and everything should be back running properly now 🤗

**Comment by samyaksgupta** [comment]
hey  @fffiloni its still not working , spaces shows queue too long and that is understandable, but when i am dockerizing it still shows inference error check inference.log while generating with the examples present, also i cannot see "use via api" section under app when its porting to my localhost, maybe cause its set to false in app.py i read it,

**Comment by alexyeoh** [comment]
i can confirm that it is now working properly on my duplicated space. thanks and great work @fffiloni
